### ISSUE TITLE
Question about crossover of GA exercise (1.2.3)

### ISSUE THREAD

**Issue by Tim-Haarman** [RUG-IDS/Course-2018#10]
For exercise 1.2.3 we need to make a function that generates new offspring using crossover. However in the lecture different variants were discussed. Should we just implement single-point crossover? Furthermore, because the list of variables is not an ordered list single-point crossover would work fine, but there is one exception. In the case a chromosome is created with 0's for all variables the (given) scoring part of the code crashes. I currently solved this by setting one random bit of the chromosome to 1 in this exceptional case, is this a correct way to do this or should a different heuristic/crossover method be used for this?

I currently also created some mock data myself and I think my implementation works, but maybe it would also be nice if we could get a small set of variables and labels to test it with.

**Comment by geazzo** [comment]
Since in the exercise we are dealing with feature selection and hence with binary string encoding, a single-point crossover is sufficient. You are free, however, to implement other point crossovers too, but no further sophisticated method, such as PMX, is needed.

As to your other point, it is highly unlikely that we end up with chromosomes that are full of zeros. This is because the way the generateInitialPopulation function is implemented guarantees that at least half of the bits are ones. Having said that, however, it would be very good to add an additional check and implement the solution that you propose in order to avoid all-zero chromosomes.

**Comment by Tim-Haarman** [comment]
@geazzo Alright, thanks for the quick answer. For me with my (small) set of test variables it happened basically every time within a few epochs. This was probably due to the fact that my tests only had 5 variables and 6 cases. 

Maybe for reasons like this it could be useful if some data to use as input could be included in the exercise to run the GA on, unless having to create a decently sized mock dataset was intended as part of the exercise. In the latter case maybe some instructions about what the data should look like (in terms of properties) could lift some confusion.

Kind regards,
Tim

**Comment by geazzo** [comment]
Dear Tim,

If you move on to the next question of the assignment you will find a script that I made available called myFeatureSelectionWithGA.m. That scripts include loading of face images and forming them into feature vectors. This should help.

Best regards,
George

**Comment by Tim-Haarman** [comment]
@geazzo Ah, I didn't realise yet that that question was a continuation of 1.2.3. Thanks for the response!

Kind regards,
Tim

**Comment by geazzo** [comment]
You're welcome! Success!
