### ISSUE TITLE
text analysis zipf fit

### ISSUE THREAD

**Issue by Orest-Divintari** [RUG-IDS/Course-2018#39]
I have some questions regarding the second exercise of the Text Analysis assignment

Verify that the word frequencies follow Zipf’s law, by plotting the frequency of the words vs. the rank of the words on a log-log scale. Plot the best-fitting Zipf distribution as well in the same figure. 

1) Do I have to follow the TFshake example and exclude punctuations and the words with length < 4 ? 
2) After the plot of the frequency vs rank of the words on a log-log scale, we have to plot the best-fitting Zipf distribution. I’m not sure what do you mean by best-fitting. The “ideal” zipf plot is a straight diagonal line right ? Do we have to transform it in order to approach a straight line ?

**Comment by rm-bwana** [comment]
Hello,

1. The TFShake example is a good start to the process yes. But do not follow it blindly. You need to be able to justify why you are excluding/including certain things. Simply saying because the example stated so will not be sufficient.

2. As mentioned in another issue already. You can plot the line of best fit in the original scale and then log transform both. 

All the best,
Rob.

**Comment by Orest-Divintari** [comment]
1) Do we have to clean the text for all the exercises ?
