### ISSUE TITLE
Using external libraries

### ISSUE THREAD

**Issue by RUKip** [RUG-IDS/Course-2018#49]
Hi,

Just to be sure, we were wondering if we could use external libraries for kmeans, sampling and dendograms etc. The questions seem to focus more on the data and analysis then the code, so we are assuming we don't need to implement these parts ourselves.

Kind regards,
Team 18

**Comment by rm-bwana** [comment]
Hello,

No you do not need to implement them yourselves, unless otherwise clearly stated. 

For GMM you will have to provide your own pseudocode and in the bonus question you will create your own implementation. 

Besides these we do not limit you on what you can use as long as there are sufficient instructions so that we may run your code as well.

Rob.
