### ISSUE TITLE
Type of questions on exam

### ISSUE THREAD

**Issue by fabero** [RUG-IDS/Course-2018#65]
I was wondering: do we have to be able to calculate things like eigenvalues or perform ANOVA on the exam? If not, what _do_ we have to be able to do?

**Comment by Pringled** [comment]
I'm wondering this as well, what calculations are we supposed to know by heart?

**Comment by rm-bwana** [comment]
Hello all, 

Although I cannot guarantee it for the upcoming exam, the calculations required in the mock exam are a good indication of what is required (excluding Topic 2 in the mock exam regarding Association Rules).

I would say you should know how to calculate:
- mean
- std deviation and variance (sample? population?)
- co-variance matrix
- Eigen vectors/values
- ANOVA (Sum of squares, Degrees of Freedom, Mean of Squares, F-statistic)*
- The basic dissimilarity metrics (euclidean, manhattan)
- Gini, Entropy, Classification error (and the associated gain calculations) (log_2 or log_10)? 
- Term Frequency (TF)
- Inverse Document Frequency (IDF) and of course combining them into TF.IDF
- The basic linkage types (single link, complete link, average link, centroids)

*More than this would require a lookup table or diagram of the F-distribution so I am not too sure about this in an exam setting.

While this answer is no guarantee and you cannot claim anything based on this answer it is in my opinion what would be required. The only guarantee would be going through all the lecture slides and ensuring you know every single calculation that appears, but the list above is quite extensive and should cover a large part of the mathematical formulae you would need to know. 

As mentioned in the final tutorial, you would also need to know the structure of the major algorithms you covered over the course (KNN, DTs, K-means, GAs, etc.) You will not need to calculate the output of an entire algorithm but you should know what they are made of and in what order. 

Rob.

**Comment by dcodrut** [comment]
Hi,

Regarding the TF.IDF, I've seen that there are multiple versions for it. Should we use the following one in the exam? 

<a href="https://www.codecogs.com/eqnedit.php?latex=TF(term,&space;doc)&space;=&space;ln(\frac{<\text{count&space;of&space;}&space;term&space;\text{&space;in&space;}&space;doc>}{<\text{count&space;words&space;in&space;}doc>})&space;\\&space;\\&space;\\&space;IDF(term,&space;docs)&space;=&space;ln(\frac{N&space;&plus;&space;1}{<\text{number&space;of&space;}&space;docs&space;\text&space;{&space;containing&space;}&space;term>&space;&plus;&space;1})&plus;1" target="_blank"><img src="https://latex.codecogs.com/gif.latex?TF(term,&space;doc)&space;=&space;ln(\frac{<\text{count&space;of&space;}&space;term&space;\text{&space;in&space;}&space;doc>}{<\text{count&space;words&space;in&space;}doc>})&space;\\&space;\\&space;\\&space;IDF(term,&space;docs)&space;=&space;ln(\frac{N&space;&plus;&space;1}{<\text{number&space;of&space;}&space;docs&space;\text&space;{&space;containing&space;}&space;term>&space;&plus;&space;1})&plus;1" title="TF(term, doc) = ln(\frac{<\text{count of } term \text{ in } doc>}{<\text{count words in }doc>}) \\ \\ \\ IDF(term, docs) = ln(\frac{N + 1}{<\text{number of } docs \text { containing } term> + 1})+1" /></a>

I confused because I don't get why we add plus 1 everywhere in the IDF, even after log is applied, but not even once in the TF term. I also tried to correlate it with the results from TF.IDF Notebook provided, but there I think they use only the "count  of term in doc"  as TF term (so it's not even divided by the "total number of words in doc" as in the above formula).
