### ISSUE TITLE
Course literature planning

### ISSUE THREAD

**Issue by Loes-Deuling** [RUG-IDS/Course-2018#7]
Hello, 
I was wondering if there would be a planning available for the course material that we should study for the exam. In the lecture the book of Tan was mentioned, and the first few sections of the book cover a lot of what discussed in the lecture. However, there is no specifications on which sections/subsections would be relevant. Also, the other book needed according to Ocasys has never been mentioned at all. Is it possible for the professors/TA's to provide us a list of the material that we should study?
Thank you.

**Comment by rm-bwana** [comment]
Hello @Loes-Deuling,

Do you mean you would like this list beforehand? It is normally the case that the lecture slides cover the material and you can do further reading in the textbooks. 

The exam would not ask anything not included in the lecture slides, so the textbooks are for you to further expand your knowledge of what was covered in class.

Rob.

**Comment by Loes-Deuling** [comment]
Hello @rm-bwana,

Thank you for the reply. A list would be handy, but if the lecture slides cover everything, I will use them then as a guide what to read. 

Loes

**Comment by rm-bwana** [comment]
@Loes-Deuling,
Disclaimer: the lecture notes cover all the topics. Not everything. It may sounds the same but there is a difference:
I am not saying that if you read only the slides you will know everything there is to know. 
I am saying that every topic which you would be required to know will be mentioned and introduced in the slides. 

Rob.

**Comment by Loes-Deuling** [comment]
@rm-bwana 
Thank you for the clarification.

Loes

**Comment by Loes-Deuling** [comment]
Hello @rm-bwana 

I saw on nestor the notification about the sources used for the lectures. These are the two books also stated on Ocasys, and are indeed mentioned at the end of the slides as reference (but without chapters). Is there an update on the possible publication of a detailed chapter planning? 

Kind regards
Loes

**Comment by rm-bwana** [comment]
Hello,

The lectures are continuously being updated to remain relevant. Due to this, while the following list should touch on everything covered in the course, be on the lookout for things that I may not have mentioned. The following list is based on the _Introduction to Data Mining_ book by Tan _et al._.

- Chapter 2 (all), Data. This was not only covered in the first lectures but will be part of future lectures as well.
- Chapter 3 (3.3) Visualisation. Most of the summary statistics section is considered required knowledge from beforehand, while OLAP and MultiDimensional Data is covered in other courses and so we do not cover it here.
- Chapter 4 (mostly all) Classification. This will be one of the bigger topics for this course so I would advise you read up on this when you can. We will be covering Decision Trees among other algo's  and Model Overfitting and Evaluation will be a big part of the upcoming lectures.
- Chapter 5 (5.2, 5.6, 5.7) Nearest Neighbour was covered last week already while Ensemble Methods and Class Imbalance will feature soon. The other sections in this book are part of other courses (Bayesian and SVM in Pattern Recognition, Artificial Neural Networks in Neural Networks and Computational Intelligence) so you can read ahead for those courses if you want to do them later, but they will probably have their own reading material which may be better suited.
- Chapter 6 (skip), This was in previous iterations of the course but is now part of the Information Systems course conducted by George Azzopardi in the upcoming semesters.
- Chapter 7 (skip). This is very much advanced concepts and you won't be taught them unless you specialise in that particular direction.
- Chapter 8 (all but potentially not 8.4) This will be covered in the topic 'unsupervised methods'. Clustering is something you will encounter numerous times in Data Science. K-means, agglomerative, and cluster evaluation will be covered. The DBSCAN algo will likely not be touched on but wait to see in the lecture itself. 
- Chapter 9 (skip) This chapter would only be recommended if you are going into this field in particular. It is not required for this course.
- Chapter 10 (skip) Not covered.

The Text Analysis lecture will be based on it's own material.

**Comment by Loes-Deuling** [comment]
Thank you very much for the update. I will keep an eye on the lecture notes, and study according to this list.
